"""add css to page_pres

Revision ID: dc21e1cd720c
Revises: f3aa6b638605
Create Date: 2026-09-19 18:02:25.289375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc21e1cd720c'
down_revision: Union[str, Sequence[str], None] = 'f3aa6b638605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_pres', sa.Column('css', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_pres', 'css')
    # ### end Alembic commands ###
