"""add users.policy and users.rules

Revision ID: fe4f2cf832bb
Revises: b34d42853cc7
Create Date: 2026-10-06 04:03:40.863477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe4f2cf832bb"
down_revision: Union[str, Sequence[str], None] = "b34d42853cc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("policy", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("rules", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rules")
    op.drop_column("users", "policy")
    # ### end Alembic commands ###
