"""add page_pres, page_hist, page_chat

Revision ID: c2eadcf4d8d6
Revises: 393892ff52a9
Create Date: 2026-09-18 02:39:13.523117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c2eadcf4d8d6"
down_revision: Union[str, Sequence[str], None] = "393892ff52a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_pres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("is_delete", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_page_pres_created_at", "page_pres", ["created_at"], unique=False
    )
    op.create_index(
        "idx_page_pres_is_delete", "page_pres", ["is_delete"], unique=False
    )
    op.create_table(
        "page_chat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_page_chat_created_at", "page_chat", ["created_at"], unique=False
    )
    op.create_index(
        "idx_page_chat_page_created",
        "page_chat",
        ["page_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_page_chat_page_id", "page_chat", ["page_id"], unique=False
    )
    op.create_table(
        "page_hist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_page_hist_created_at", "page_hist", ["created_at"], unique=False
    )
    op.create_index(
        "idx_page_hist_page_created",
        "page_hist",
        ["page_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_page_hist_page_id", "page_hist", ["page_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_page_hist_page_id", table_name="page_hist")
    op.drop_index("idx_page_hist_page_created", table_name="page_hist")
    op.drop_index("idx_page_hist_created_at", table_name="page_hist")
    op.drop_table("page_hist")
    op.drop_index("idx_page_chat_page_id", table_name="page_chat")
    op.drop_index("idx_page_chat_page_created", table_name="page_chat")
    op.drop_index("idx_page_chat_created_at", table_name="page_chat")
    op.drop_table("page_chat")
    op.drop_index("idx_page_pres_is_delete", table_name="page_pres")
    op.drop_index("idx_page_pres_created_at", table_name="page_pres")
    op.drop_table("page_pres")
    # ### end Alembic commands ###
