"""add runs table

Revision ID: 3f36f610bcc5
Revises: 4f41c40a18ab
Create Date: 2026-09-23 08:05:18.806456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3f36f610bcc5"
down_revision: Union[str, Sequence[str], None] = "4f41c40a18ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("block_catalog", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("filled", sa.Text(), nullable=True),
        sa.Column("effects", sa.Text(), nullable=True),
        sa.Column("final_html", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_runs_page_id", "runs", ["page_id"], unique=False)
    op.create_index(
        "idx_runs_page_status", "runs", ["page_id", "status"], unique=False
    )
    op.create_index("idx_runs_status", "runs", ["status"], unique=False)
    op.create_index("idx_runs_user_id", "runs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_runs_user_id", table_name="runs")
    op.drop_index("idx_runs_status", table_name="runs")
    op.drop_index("idx_runs_page_status", table_name="runs")
    op.drop_index("idx_runs_page_id", table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
