"""initial

Revision ID: 393892ff52a9
Revises:
Create Date: 2026-09-17 02:53:05.898166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "393892ff52a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=True),
        sa.Column("can_write", sa.Boolean(), nullable=True),
        sa.Column("is_delete", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_access_is_delete", "access", ["is_delete"], unique=False
    )
    op.create_index(
        "idx_access_user_module",
        "access",
        ["user_id", "module_id"],
        unique=True,
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("is_delete", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_modules_is_delete", "modules", ["is_delete"], unique=False
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_json", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.Column("is_delete", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("rss_yandex_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_pages_datetime", "pages", ["datetime"], unique=False)
    op.create_index(
        "idx_pages_is_active", "pages", ["is_active"], unique=False
    )
    op.create_index(
        "idx_pages_is_delete", "pages", ["is_delete"], unique=False
    )
    op.create_index(
        "idx_pages_rss_yandex_id", "pages", ["rss_yandex_id"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("subsys", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("caption", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_delete", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_settings_is_delete", "settings", ["is_delete"], unique=False
    )
    op.create_index(
        "idx_settings_lookup",
        "settings",
        ["domain", "subsys", "module", "section", "key"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column(
            "is_superadmin",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_index(
        "idx_users_is_delete", "users", ["is_delete"], unique=False
    )
    op.create_index("idx_users_login", "users", ["login"], unique=False)
    op.create_table(
        "nav",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("card_type", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("module_id", sa.Integer(), nullable=True),
        sa.Column("is_delete", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["nav.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_nav_is_delete", "nav", ["is_delete"], unique=False)
    op.create_index("idx_nav_module_id", "nav", ["module_id"], unique=False)
    op.create_index("idx_nav_parent", "nav", ["parent_id"], unique=False)
    op.create_index("idx_nav_type", "nav", ["card_type"], unique=False)
    op.create_index("idx_nav_user_id", "nav", ["user_id"], unique=False)
    op.create_table(
        "password_resets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("password_resets")
    op.drop_index("idx_nav_user_id", table_name="nav")
    op.drop_index("idx_nav_type", table_name="nav")
    op.drop_index("idx_nav_parent", table_name="nav")
    op.drop_index("idx_nav_module_id", table_name="nav")
    op.drop_index("idx_nav_is_delete", table_name="nav")
    op.drop_table("nav")
    op.drop_index("idx_users_login", table_name="users")
    op.drop_index("idx_users_is_delete", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_settings_lookup", table_name="settings")
    op.drop_index("idx_settings_is_delete", table_name="settings")
    op.drop_table("settings")
    op.drop_index("idx_pages_rss_yandex_id", table_name="pages")
    op.drop_index("idx_pages_is_delete", table_name="pages")
    op.drop_index("idx_pages_is_active", table_name="pages")
    op.drop_index("idx_pages_datetime", table_name="pages")
    op.drop_table("pages")
    op.drop_index("idx_modules_is_delete", table_name="modules")
    op.drop_table("modules")
    op.drop_index("idx_access_user_module", table_name="access")
    op.drop_index("idx_access_is_delete", table_name="access")
    op.drop_table("access")
    # ### end Alembic commands ###
