"""add domains table correсt

Revision ID: 8d7a5c96eb43
Revises: 3c1a90581989
Create Date: 2026-10-02 08:16:23.265607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d7a5c96eb43"
down_revision: Union[str, Sequence[str], None] = "3c1a90581989"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("disabled_at", sa.DateTime(), nullable=False),
        sa.Column("delete_after", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        "idx_domains_delete_after", "domains", ["delete_after"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_domains_delete_after", table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
