"""remove_root_node_id

Revision ID: f14984e73518
Revises: 99c8ec4a8e5c
Create Date: 2026-05-30 18:37:59.096192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f14984e73518"
down_revision: Union[str, Sequence[str], None] = "99c8ec4a8e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "root_node_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("root_node_id", sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
