"""Initial migration with new models

Revision ID: 99c8ec4a8e5c
Revises:
Create Date: 2026-05-29 09:07:13.041517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "99c8ec4a8e5c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_modules_is_delete", "modules", ["is_delete"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("subsys", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("caption", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_settings_is_delete", "settings", ["is_delete"], unique=False
    )
    op.create_index(
        "idx_settings_lookup",
        "settings",
        ["domain", "subsys", "module", "section", "key"],
        unique=True,
    )
    op.create_table(
        "tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("columns_json", sa.Text(), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tables_is_delete", "tables", ["is_delete"], unique=False
    )
    op.create_index("idx_tables_user_id", "tables", ["user_id"], unique=False)
    op.create_index(
        "idx_tables_user_name", "tables", ["user_id", "name"], unique=True
    )
    op.create_table(
        "user_module_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column(
            "can_read",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "can_write",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_up_is_delete",
        "user_module_permissions",
        ["is_delete"],
        unique=False,
    )
    op.create_index(
        "idx_up_user_module",
        "user_module_permissions",
        ["user_id", "module_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column(
            "is_superadmin",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("root_node_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_users_is_delete", "users", ["is_delete"], unique=False
    )
    op.create_index("idx_users_login", "users", ["login"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("node_type", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("module_id", sa.Integer(), nullable=True),
        sa.Column(
            "is_delete",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["table_id"], ["tables.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_nodes_is_delete", "nodes", ["is_delete"], unique=False
    )
    op.create_index(
        "idx_nodes_module_id", "nodes", ["module_id"], unique=False
    )
    op.create_index("idx_nodes_parent", "nodes", ["parent_id"], unique=False)
    op.create_index("idx_nodes_type", "nodes", ["node_type"], unique=False)
    op.create_index("idx_nodes_user_id", "nodes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_nodes_user_id", table_name="nodes")
    op.drop_index("idx_nodes_type", table_name="nodes")
    op.drop_index("idx_nodes_parent", table_name="nodes")
    op.drop_index("idx_nodes_module_id", table_name="nodes")
    op.drop_index("idx_nodes_is_delete", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("idx_users_login", table_name="users")
    op.drop_index("idx_users_is_delete", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_up_user_module", table_name="user_module_permissions")
    op.drop_index("idx_up_is_delete", table_name="user_module_permissions")
    op.drop_table("user_module_permissions")
    op.drop_index("idx_tables_user_name", table_name="tables")
    op.drop_index("idx_tables_user_id", table_name="tables")
    op.drop_index("idx_tables_is_delete", table_name="tables")
    op.drop_table("tables")
    op.drop_index("idx_settings_lookup", table_name="settings")
    op.drop_index("idx_settings_is_delete", table_name="settings")
    op.drop_table("settings")
    op.drop_index("idx_modules_is_delete", table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
