"""add css to pages and page_hist

Revision ID: 2c514382be88
Revises: 3f36f610bcc5
Create Date: 2026-09-24 03:04:03.315603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2c514382be88"
down_revision: Union[str, Sequence[str], None] = "3f36f610bcc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page_hist", sa.Column("css", sa.Text(), nullable=True))
    op.add_column("pages", sa.Column("css", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "css")
    op.drop_column("page_hist", "css")
    # ### end Alembic commands ###
