"""drop llm table

Revision ID: 0fee0a076f0b
Revises: 2c514382be88
Create Date: 2026-09-24 07:39:56.845733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0fee0a076f0b"
down_revision: Union[str, Sequence[str], None] = "2c514382be88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("provider", sa.VARCHAR(length=32), nullable=False),
        sa.Column("model", sa.VARCHAR(length=64), nullable=True),
        sa.Column("max_output_tokens", sa.INTEGER(), nullable=True),
        sa.Column("timeout", sa.INTEGER(), nullable=True),
        sa.Column("deepseek_api_key_enc", sa.BLOB(), nullable=True),
        sa.Column("openai_api_key_enc", sa.BLOB(), nullable=True),
        sa.Column("yandex_api_key_enc", sa.BLOB(), nullable=True),
        sa.Column("yandex_folder_id_enc", sa.BLOB(), nullable=True),
        sa.Column("gigachat_auth_key_enc", sa.BLOB(), nullable=True),
        sa.Column("gigachat_ca_pem_enc", sa.BLOB(), nullable=True),
        sa.Column("gemini_api_key_enc", sa.BLOB(), nullable=True),
        sa.Column("updated_by", sa.INTEGER(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
