"""users.domain

Revision ID: c0ad66f18caa
Revises: 6b80633ef790
Create Date: 2026-10-01 07:28:25.994756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c0ad66f18caa"
down_revision: Union[str, Sequence[str], None] = "6b80633ef790"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("domain", sa.String(length=253), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "domain")
    # ### end Alembic commands ###
