"""add pages.url

Revision ID: bd36e37c3294
Revises: fe4f2cf832bb
Create Date: 2026-10-07 07:06:53.052108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bd36e37c3294"
down_revision: Union[str, Sequence[str], None] = "fe4f2cf832bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pages", sa.Column("url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "url")
    # ### end Alembic commands ###
